Repository aidenmendez/Crate, pull requests merged in 2021-04, with the labels that each got.

#66 User products
  code/api/package-lock.json
  code/api/src/migrations/5-user_products.js
  code/api/src/modules/user/tests/userQuery.test.js
  code/api/src/modules/userProduct/model.js
  code/api/src/modules/userProduct/mutations.js
  code/api/src/modules/userProduct/query.js
  code/api/src/modules/userProduct/resolvers.js
  code/api/src/modules/userProduct/types.js
  code/api/src/seeders/4-userProducts.js
  code/api/src/setup/models.js
  code/api/src/setup/schema/queries.js
Labels: backend

#67 Subscription update
  code/api/src/migrations/7-add_columns_to_user_table.js
  code/api/src/modules/subscription/mutations.js
  code/api/src/modules/subscription/resolvers.js
  code/api/src/modules/subscription/types.js
  code/api/src/seeders/1-user.js
Labels: backend

#68 Feature/display subscriptions
  code/web/src/modules/user/Profile.js
Labels: FE, react, redux

#69 Fix zip code in user mutation to expect string
  code/api/src/modules/user/mutations.js
Labels: backend

#70 Feature/update user profile
  code/api/package-lock.json
  code/api/src/modules/user/model.js
  code/api/src/modules/user/query.js
  code/api/src/modules/user/types.js
  code/web/src/modules/user/Profile.js
Labels: FE, bug, enhancement, graphQL, react, redux, styling

#72 Feature/cypress testing
  code/cypress.json
  code/web/cypress.json
  code/web/cypress/fixtures/example.json
  code/web/cypress/integration/Profile_spec.js
  code/web/cypress/plugins/index.js
  code/web/cypress/support/commands.js
  code/web/cypress/support/index.js
  code/web/package-lock.json
  code/web/package.json
  cypress.json
Labels: FE, react, testing
