Repository aidenmendez/Crate, pull requests merged in 2021-03, with the labels that each got.

#28 Display message when there are no related items.
  code/api/package-lock.json
  code/package-lock.json
  code/web/package-lock.json
  code/web/package.json
  code/web/src/modules/product/Detail.js
  code/web/src/modules/product/Related.js
Labels: FE, bug

#54 Add Redux dev tools and composeWithDevTools
  code/web/package-lock.json
  code/web/package.json
  code/web/src/setup/store.js
Labels: redux

#57 Create migrations
  code/api/src/migrations/5-user_products.js
  code/api/src/migrations/6-crate_products.js
  code/api/src/migrations/7-add_columns_to_user_table.js
  code/api/src/migrations/8-add_delivery_date_to_subscriptions_table.js
Labels: backend, database, migrations

#61 Feature/static profile
  code/web/src/modules/user/Profile.js
  code/web/src/ui/grid/Grid.js
Labels: FE, enhancement, react, styling

#62 Feature/incorporate details
  code/api/package-lock.json
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/api/actions.js
  code/web/src/modules/user/api/state.js
  code/web/src/ui/image/Tile.js
Labels: FE, enhancement
